var car = "Sabaru";
console.log("Is car == 'Sabaru'? I predict True");
console.log(car == "Sabaru");
console.log("Is car !== 'Sabaru'? I predict False");
console.log(car !== "Sabaru");
console.log("Is car !== 'Honda'? I predict True");
console.log(car !== "Honda");
console.log("Is car == 'Honda'? I predict False");
console.log(car == "Honda");
console.log("Is car == 'Ford'? I predict False");
console.log(car == "Ford");
console.log("Is car !== 'Ford'? I predict True");
console.log(car !== "Ford");
console.log("Is car !== 'Toyota'? I predict True");
console.log(car !== "Toyota");
console.log("Is car == 'Toyota'? I predict False");
console.log(car == "Toyota");
console.log("Is car == 'Suzuki'? I predict False");
console.log(car == "Suzuki");
console.log("Is car !== 'Suzuki'? I predict True");
console.log(car !== "Suzuki");
